#!/bin/bash

# Setup API Environment Script
# Automatically creates .env file with API Gateway configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$MOBILE_DIR")"
BACKEND_DIR="$PROJECT_ROOT/backend"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "🔧 Setting up API environment configuration..."
echo ""

# Check if LocalStack is running
if ! curl -s http://localhost:4566/_localstack/health > /dev/null 2>&1; then
    echo -e "${RED}❌ LocalStack is not running!${NC}"
    echo "Please start LocalStack first:"
    echo "  cd backend && npm run localstack:start"
    exit 1
fi

echo -e "${GREEN}✅ LocalStack is running${NC}"
echo ""

# Detect AWS CLI command
AWS_CMD=""
if command -v awslocal >/dev/null 2>&1; then
    AWS_CMD="awslocal"
elif command -v aws >/dev/null 2>&1; then
    AWS_CMD="aws --endpoint-url=http://localhost:4566"
else
    echo -e "${RED}❌ Neither 'awslocal' nor 'aws' command found${NC}"
    echo "Please install awscli-local:"
    echo "  pip install awscli-local"
    exit 1
fi

echo "Using AWS command: $AWS_CMD"
echo ""

# Try to get API URL from CloudFormation stack outputs first
echo "🔍 Checking CloudFormation stack outputs..."
STACK_NAME="mufradat-local"
API_URL=""
API_ID=""
STAGE="v1"

if $AWS_CMD cloudformation describe-stacks --stack-name "$STACK_NAME" > /dev/null 2>&1; then
    echo "✅ Found stack: $STACK_NAME"
    
    # Get API URL from outputs
    API_URL=$($AWS_CMD cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
        --output text 2>/dev/null || echo "")
    
    # Get stage name
    STAGE=$($AWS_CMD cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --query 'Stacks[0].Outputs[?OutputKey==`ApiStage`].OutputValue' \
        --output text 2>/dev/null || echo "v1")
    
    if [ -z "$STAGE" ] || [ "$STAGE" = "None" ]; then
        STAGE="v1"
    fi
    
    if [ -n "$API_URL" ] && [ "$API_URL" != "None" ]; then
        echo -e "${GREEN}✅ Found API URL in stack outputs${NC}"
        # Extract API ID from URL
        if echo "$API_URL" | grep -q "execute-api"; then
            API_ID=$(echo "$API_URL" | sed -E 's|https?://([^.]+)\.execute-api.*|\1|' || echo "")
        else
            API_ID=$(echo "$API_URL" | sed -E 's|.*/restapis/([^/]+).*|\1|' || echo "")
        fi
    fi
fi

# If we don't have API URL, try to get API Gateway ID directly
if [ -z "$API_URL" ] || [ -z "$API_ID" ]; then
    echo "🔍 Getting API Gateway ID from LocalStack..."
    API_ID=$($AWS_CMD apigateway get-rest-apis --query 'items[0].id' --output text 2>/dev/null || echo "")
    
    if [ -z "$API_ID" ] || [ "$API_ID" = "None" ]; then
        echo -e "${RED}❌ Could not find API Gateway${NC}"
        echo "Please deploy backend first:"
        echo "  cd backend && npm run deploy:local"
        exit 1
    fi
    
    # Construct API URL using execute-api format
    API_URL="https://${API_ID}.execute-api.localhost.localstack.cloud:4566/${STAGE}"
    echo -e "${GREEN}✅ Constructed API URL from API Gateway ID${NC}"
fi

echo ""
echo -e "${GREEN}📋 API Configuration:${NC}"
echo "   API Gateway ID: $API_ID"
echo "   Stage: $STAGE"
echo "   API URL: $API_URL"
echo ""

# Create .env file
ENV_FILE="$MOBILE_DIR/.env"

# Backup existing .env if it exists
if [ -f "$ENV_FILE" ]; then
    BACKUP_FILE="${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "📦 Backing up existing .env to $BACKUP_FILE"
    cp "$ENV_FILE" "$BACKUP_FILE"
fi

# Write .env file
cat > "$ENV_FILE" << EOF
# API Configuration
# Generated by setup-api-env.sh on $(date)

# Full API Base URL (recommended - use this)
EXPO_PUBLIC_API_BASE_URL=$API_URL

# Alternative: API Gateway ID (URL will be constructed)
# EXPO_PUBLIC_API_ID=$API_ID
# EXPO_PUBLIC_API_STAGE=$STAGE

# Note: If you set EXPO_PUBLIC_API_BASE_URL, the other variables are ignored
EOF

echo -e "${GREEN}✅ Created .env file at: $ENV_FILE${NC}"
echo ""
echo "📝 Contents:"
cat "$ENV_FILE"
echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the .env file if needed"
echo "  2. Start your Expo app: npm start"
echo "  3. The app will automatically use the API URL from .env"
echo ""
echo "💡 Tips:"
echo "  - If you redeploy and get a new API ID, run: npm run setup:api"
echo "  - The .env file is gitignored (won't be committed)"
echo "  - See .env.example for the template format"
